name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Tests with Maven
        run: |
          pwd
          ls
          cd Aula-GitHub-Actions
          mvn clean test site

      - name: Upload artefatos
        uses: actions/upload-artifact@v3
        with:
          name: relatorio-testes
          path: Aula-GitHub-Actions/target/site/

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          pwd
          ls
          cd Aula-GitHub-Actions
          mvn clean install

      - name: Upload artefatos
        uses: actions/upload-artifact@v3
        with:
          name: Pacote
          path: Aula-GitHub-Actions/target/*.jar

  notification:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Instalar mailutils
        run: sudo apt-get update && sudo apt-get install -y mailutils

      - name: Listar arquivos no diretório scripts
        run: ls -la scripts

      - name: Enviar e-mail de notificação
        run: scripts/send_email.sh
        env:
          RECIPIENT: ${{ secrets.EMAIL }}  # E-mail do destinatário